In [4]:
%cd /4tb/nabarun/nlp/DLNLP/text_gcn

/4tb/nabarun/nlp/DLNLP/text_gcn


In [2]:
!ls

README.md	 data	     plot_dim.py      train.py
__init__.py	 doc2vec.py  plot_prop.py     utils.py
__pycache__	 inits.py    plot_window.py   visualize.py
bow.py		 layers.py   prepare_data.py  visualize_words.py
build_corpus.py  metrics.py  remove_words.py  wordnet.py
build_graph.py	 models.py   results


In [5]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py 20ng

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'itself', "mightn't", 'o', 'mightn', 'only', "don't", 'myself', 'other', 'these', 'shan', "should've", "wouldn't", "weren't", "it's", 'herself', 'm', "you'd", 'this', 'was', 'hasn', 'couldn', 'off', 'most', 're', 'here', "isn't", 'needn', 'under', 'in', 'than', 'at', 'having', 'once', 'our', 'can', "she's", 'very', 'and', 'who', 'hers', 'further', 'her', 'just', 'themselves', 'how', 'into', 'about', 'he', 'all', 'through', 'my', 'have', 'until', "aren't", 'mustn', 'wouldn', 'am', 'haven', 'me', 'there', 'ourselves', 'were', 'more', 'the', 'weren', 'll', 'shouldn', "that'll", 'whom', 'did', 'do', 'won', 'both', 'between', 'from', "shan't", 'yours', 'you', "mustn't", 'a', 'nor', 'over', 'each', 'we', "you'll", 'few', 'will', "doesn't", 'where', 'an', "hasn't", 'are', 'that', "needn't", 'on', 'his', 'she', "you're", 'such', 'some', 'yourselves', '

In [9]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py R8

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'we', 'before', 'while', 'at', 'below', 'will', "isn't", 'our', 'above', 'their', 'was', 'my', 'after', "you'll", 'those', 'wouldn', 'no', 'down', "shouldn't", 'shan', 'having', 'o', 'once', 'd', 'as', 'in', 'been', 'i', 'here', 'ours', 'each', 'some', 'should', 'to', 'with', 'the', 'there', "wouldn't", 'y', 'mustn', 'll', 'very', 'yourself', 'only', 'did', 'don', 'yours', 'by', 'on', 'an', "couldn't", 'any', 'does', 'm', 'herself', 'where', "wasn't", 'him', 'what', 'nor', "shan't", 'up', 'me', 've', 'few', 'when', "you'd", 'that', 'if', 'but', 'own', "hadn't", 'himself', 'for', "needn't", "weren't", 'which', 'is', 'mightn', 'he', 'of', 'doing', 'hadn', 'itself', "aren't", 'how', 'it', 'who', 'further', 'themselves', 'too', 'over', 'off', 'between', 'couldn', 'her', 'until', 'a', 'most', 'isn', 'won', "that'll", 'whom', 'this', 'his', 'why', 'n

In [12]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py R52

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{"that'll", "aren't", 'because', 'how', 'whom', 'some', 'was', "won't", 'for', 'in', 'why', 'off', "shouldn't", 'with', 'about', 'hers', 'don', "weren't", "didn't", 'any', 'he', 'who', "you're", "wasn't", 'up', 'wouldn', 'the', 'doing', 'most', 'didn', 'each', 'ourselves', 'only', "hadn't", 'y', "hasn't", "she's", 'while', 'our', "you've", 'until', 'after', 'down', 'there', 't', 'can', 'same', 'haven', 'over', 'than', 'this', 'itself', 'ain', 'theirs', 'hasn', 'few', "shan't", 'before', 'here', 'no', 'won', 'more', 'mustn', 'and', 'such', "wouldn't", 'me', 'we', 'i', 'that', "couldn't", 'it', 'by', 'his', 'myself', 'as', 'o', 'be', 'weren', 'aren', 'is', 'below', "mustn't", 'not', "isn't", 'having', 'did', 'once', 'too', 'll', 'had', 'will', 'at', 'has', 'then', 'just', 'wasn', 'under', 'of', "needn't", 'again', 'between', 'above', 'into', 'they

In [13]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py ohsumed

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'couldn', 'ours', 'until', 'through', 'above', "hasn't", "you're", 'me', 'between', 'where', 'other', 'while', 'it', 'she', 'y', 'mustn', 'why', "shouldn't", 'few', 'can', 'should', 'about', 'its', 'won', 'for', 'isn', 'on', "that'll", 'yourselves', "wouldn't", 'him', 'own', 'if', 'your', 'weren', "weren't", "you've", 'again', 's', 'mightn', 'ain', 'you', 'has', 'i', 've', 'below', "won't", 'only', 'theirs', 'our', 'then', 'hers', 'who', 'hasn', 'been', 'doing', 'itself', 'did', 'at', 'don', 'that', 'o', "couldn't", 'shouldn', 'have', 'just', 'to', 'we', "shan't", 'm', 'in', 'himself', 'those', 'or', 'up', 'into', 'not', 'these', 'being', 'yours', 'more', 'shan', 'over', 'myself', 't', 'an', 'further', 'they', 'wouldn', 'both', 'the', 'any', "wasn't", 'there', "don't", 'their', 'he', 'were', 'ourselves', 'now', 'didn', "doesn't", 'most', "mustn

In [14]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py mr

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'myself', 'will', 'am', 'y', "aren't", 'in', 'were', 'was', 'themselves', "couldn't", 'won', 'them', "hasn't", 'being', 'why', 'shouldn', "wouldn't", 'very', 'had', 'no', 'about', 'ourselves', "don't", 'each', 'ain', 'again', 'under', 'they', 'hasn', 'these', "mightn't", "you're", 'those', 'too', 'over', 'aren', 'mustn', "weren't", "isn't", 'yourself', "it's", 'our', 'into', 'can', 'then', 'against', 'the', 'ma', 'between', "you'll", 'you', 'its', 'does', 'off', "that'll", 'it', 'or', 'this', 'where', 'theirs', 'isn', 'own', 'having', 'below', 'up', "you'd", 'once', 'not', 'an', 'me', 'from', 'hers', 'any', 'only', "haven't", 'his', 't', 'whom', 'a', 'there', 'didn', 'she', "shouldn't", 'm', "didn't", "she's", 'hadn', 'shan', 'i', "doesn't", 'has', 'yours', 'my', 'weren', 'what', 'until', 'further', 'ours', 'and', 'have', 'but', "won't", 's', '

In [7]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py cora

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'whom', 'to', 'myself', 'it', 'just', "you'll", 'your', 'through', 'own', 'them', 'both', 'no', 'wasn', 've', 'when', 'why', 'nor', "shan't", 'in', 'by', 'hadn', 'd', 'a', 'again', 'against', 'is', 'but', 'where', "doesn't", 'because', 'of', "haven't", 'under', 'any', 'up', 'themselves', 'don', 'does', 'not', 're', 'herself', "she's", 'shan', "hadn't", "you've", "won't", 'at', 'our', "isn't", 'such', 'than', "you'd", 'having', 'who', 'shouldn', "wasn't", 'during', 'yourselves', 'here', 'i', 'have', "don't", 'are', 'those', 'some', 'been', 'their', 'doing', 'there', 'll', 'doesn', 'himself', 'which', 'weren', 'until', 'then', "mustn't", 'her', "should've", 'ma', 'mustn', 'ours', 'yourself', 'hers', 'had', "that'll", "mightn't", 'aren', 'she', 'the', 't', 'wouldn', 'you', 'we', 'hasn', 'his', 'from', 'being', 's', 'very', 'didn', 'further', 'belo

In [8]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py pubmed

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'he', 'which', 'then', 'shan', 'had', 'don', "don't", 'by', 'isn', 'there', 'most', "shan't", 'below', 'did', "it's", 'these', "aren't", 'haven', 'through', 'how', 'can', 'after', 'm', "mustn't", "that'll", "should've", 'd', "you'd", 'nor', 'won', 'myself', 'same', 'each', 'didn', 'against', "needn't", 'at', 'too', 'a', 'all', 'yourselves', 'before', "won't", 'as', 'wasn', "she's", 'our', 'is', 'my', 'between', 'have', 'shouldn', 'from', "didn't", 'are', 'own', "hasn't", 'be', 'its', 'has', 'they', 'down', "weren't", "isn't", 'under', 'hasn', 'theirs', 'such', 'will', 'over', 'both', 'those', 'of', 'his', 'their', 'if', 'we', "doesn't", 've', 'it', 'no', 'am', 'who', 'me', 'hers', 'why', 'itself', 'during', 'hadn', 'what', 'mightn', 'off', 'only', 'been', 'were', 're', 'yours', "couldn't", 'further', 'up', "you've", 'whom', 'do', 'in', 'weren',

In [9]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py citeseer

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'against', 'are', 'them', "aren't", 'yourself', 'am', 'if', 'won', 'on', "wasn't", 'wouldn', 'most', "hasn't", 'or', 'why', "shouldn't", 'under', 'themselves', 'but', 'doesn', 'shan', "you're", 'some', 'the', 'haven', 'theirs', 'not', "didn't", 'between', 'we', 'other', 'has', 'having', 'off', "isn't", 'they', 'where', 'to', 'been', 'more', 'ma', 'our', 'were', "shan't", 'further', 'those', 'here', "haven't", 'o', 'hers', 'who', 'about', 'this', 't', 'did', 'few', 'himself', 'my', 'myself', 'until', 'an', 'being', 'does', 'had', 'of', 'with', "mightn't", 'which', 'over', "hadn't", 'out', 'i', 'now', 'mightn', 'so', "doesn't", "weren't", 'no', 'its', "you've", 'because', 'into', 'above', 'your', 'whom', 'me', "wouldn't", 'all', 've', 'doing', 'up', 'when', 'she', 'for', 'ain', 'shouldn', 'as', 'after', 'any', 'before', 'should', 'own', "you'll",

In [7]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py 20ng

[7532, 7533, 7534, 7535, 7536, 7537, 7538, 7539, 7540, 7541, 7542, 7543, 7544, 7545, 7546, 7547, 7548, 7549, 7550, 7551, 7552, 7553, 7554, 7555, 7556, 7557, 7558, 7559, 7560, 7561, 7562, 7563, 7564, 7565, 7566, 7567, 7568, 7569, 7570, 7571, 7572, 7573, 7574, 7575, 7576, 7577, 7578, 7579, 7580, 7581, 7582, 7583, 7584, 7585, 7586, 7587, 7588, 7589, 7590, 7591, 7592, 7593, 7594, 7595, 7596, 7597, 7598, 7599, 7600, 7601, 7602, 7603, 7604, 7605, 7606, 7607, 7608, 7609, 7610, 7611, 7612, 7613, 7614, 7615, 7616, 7617, 7618, 7619, 7620, 7621, 7622, 7623, 7624, 7625, 7626, 7627, 7628, 7629, 7630, 7631, 7632, 7633, 7634, 7635, 7636, 7637, 7638, 7639, 7640, 7641, 7642, 7643, 7644, 7645, 7646, 7647, 7648, 7649, 7650, 7651, 7652, 7653, 7654, 7655, 7656, 7657, 7658, 7659, 7660, 7661, 7662, 7663, 7664, 7665, 7666, 7667, 7668, 7669, 7670, 7671, 7672, 7673, 7674, 7675, 7676, 7677, 7678, 7679, 7680, 7681, 7682, 7683, 7684, 7685, 7686, 7687, 7688, 7689, 7690, 7691, 7692, 7693, 7694, 7695, 7696, 7697, 769

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

7, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, 4998, 4999, 5000, 5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, 5013, 5014, 5015, 5016, 5017, 5018, 5019, 5020, 5021, 5022, 5023, 5024, 5025, 5026, 5027, 5028, 5029, 5030, 5031, 5032, 5033, 5034, 5035, 5036, 5037, 5038, 5039, 5040, 5041, 5042, 5043, 5044, 5045, 5046, 5047, 5048, 5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059, 5060, 5061, 5062, 5063, 5064, 5065, 5066, 5067, 5068, 5069, 5070, 5071, 5072, 5073, 5074, 5075, 5076, 5077, 5078, 5079, 5080, 5081, 5082, 5083, 5084, 5085, 5086, 5087, 5088, 5089, 5090, 5091, 5092, 5093, 5094, 5095, 5096, 5097, 5098, 5099, 5100, 5101, 5102, 5103, 5104, 5105, 5106, 5107, 5108, 5109, 5110, 5111, 5112, 5113, 5

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(10183, 300) (10183, 20) (7532, 300) (7532, 20) (54071, 300) (54071, 20)


In [10]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py R8

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[5485, 5486, 5487, 5488, 5489, 5490, 5491, 5492, 5493, 5494, 5495, 5496, 5497, 5498, 5499, 5500, 5501, 5502, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518, 5519, 5520, 5521, 5522, 5523, 5524, 5525, 5526, 5527, 5528, 5529, 5530, 5531, 5532, 5533, 5534, 5535, 5536, 5537, 5538, 5539, 5540, 5541, 5542, 5543, 5544, 5545, 5546, 5547, 5548, 5549, 5550, 5551, 5552, 5553, 5554, 5555, 5556, 5557, 5558, 5559, 5560, 5561, 5562, 5563, 5564, 5565, 5566, 5567, 5568, 5569, 5570, 5571, 5572, 5573, 5574, 5575, 5576, 5577, 5578, 5579, 5580, 5581, 5582, 5583, 5584, 5585, 5586, 5587, 5588, 5589, 5590, 5591, 5592, 5593, 5594, 5595, 5596, 5597, 5598, 5599, 5600, 5601, 5602, 5603, 5604, 5605, 5606, 5607, 5608, 5609, 5610, 5611, 5612, 5613, 5614, 5615, 5616, 5617, 5618, 5619, 5620, 5621, 5622, 5623, 5624, 5625, 5626, 5627, 5628, 5629, 5630, 5631, 5632, 5633, 5634, 5635, 5636, 5637, 5638, 5639, 5640, 5641, 5642, 5643, 5644, 5645, 5646, 5647, 5648, 5649, 5650, 565

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
(4937, 300) (4937, 8) (2189, 300) (2189, 8) (13173, 300) (13173, 8)


In [15]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py R52

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[6532, 6533, 6534, 6535, 6536, 6537, 6538, 6539, 6540, 6541, 6542, 6543, 6544, 6545, 6546, 6547, 6548, 6549, 6550, 6551, 6552, 6553, 6554, 6555, 6556, 6557, 6558, 6559, 6560, 6561, 6562, 6563, 6564, 6565, 6566, 6567, 6568, 6569, 6570, 6571, 6572, 6573, 6574, 6575, 6576, 6577, 6578, 6579, 6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588, 6589, 6590, 6591, 6592, 6593, 6594, 6595, 6596, 6597, 6598, 6599, 6600, 6601, 6602, 6603, 6604, 6605, 6606, 6607, 6608, 6609, 6610, 6611, 6612, 6613, 6614, 6615, 6616, 6617, 6618, 6619, 6620, 6621, 6622, 6623, 6624, 6625, 6626, 6627, 6628, 6629, 6630, 6631, 6632, 6633, 6634, 6635, 6636, 6637, 6638, 6639, 6640, 6641, 6642, 6643, 6644, 6645, 6646, 6647, 6648, 6649, 6650, 6651, 6652, 6653, 6654, 6655, 6656, 6657, 6658, 6659, 6660, 6661, 6662, 6663, 6664, 6665, 6666, 6667, 6668, 6669, 6670, 6671, 6672, 6673, 6674, 6675, 6676, 6677, 6678, 6679, 6680, 6681, 6682, 6683, 6684, 6685, 6686, 6687, 6688, 6689, 6690, 6691, 6692, 6693, 6694, 6695, 6696, 6697, 669

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[0 0 0 ... 0 0 1]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(5879, 300) (5879, 52) (2568, 300) (2568, 52) (15424, 300) (15424, 52)


In [16]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py ohsumed

[4043, 4044, 4045, 4046, 4047, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4056, 4057, 4058, 4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4067, 4068, 4069, 4070, 4071, 4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079, 4080, 4081, 4082, 4083, 4084, 4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108, 4109, 4110, 4111, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136, 4137, 4138, 4139, 4140, 4141, 4142, 4143, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4157, 4158, 4159, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4168, 4169, 4170, 4171, 4172, 4173, 4174, 4175, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4200, 4201, 4202, 4203, 4204, 4205, 4206, 4207, 4208, 420

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[6659, 5424, 6293, 5145, 6401, 4359, 6193, 4360, 5632, 5940, 6177, 4085, 4052, 6655, 4449, 6923, 7139, 5740, 5074, 7134, 4364, 4851, 6654, 5606, 4416, 7036, 4764, 5355, 5131, 6408, 6414, 7068, 7331, 4697, 6405, 6549, 4297, 4671, 6019, 6770, 5725, 4863, 6849, 4249, 6488, 4552, 6370, 5660, 5849, 6392, 6192, 4059, 4785, 4889, 6820, 5533, 6618, 5357, 4934, 7224, 7267, 6220, 4572, 5239, 4520, 6857, 7351, 4559, 4316, 6751, 6372, 4869, 6451, 6871, 5472, 5955, 6099, 6362, 6387, 5945, 5195, 4556, 4114, 4389, 7087, 6651, 5910, 5281, 5756, 5628, 4861, 5968, 7077, 5857, 5984, 5745, 5049, 4411, 7342, 5693, 6523, 7218, 6926, 4144, 7282, 4189, 7295, 4702, 5701, 6307, 5613, 4244, 4432, 7371, 4767, 4958, 6266, 6950, 6667, 6733, 6517, 4986, 4258, 6374, 6575, 6574, 4361, 5250, 4755, 4072, 6459, 7300, 5504, 6843, 7269, 5308, 7333, 5399, 4651, 6673, 6875, 6227, 4477, 6625, 5519, 4371, 4976, 5021, 7080, 5012, 4992, 6588, 7263, 7079, 7230, 4218, 4941, 6762, 4082, 4617, 6291, 5270, 4049, 4877, 5534, 6546, 619

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3022, 300) (3022, 23) (4043, 300) (4043, 23) (17514, 300) (17514, 23)


In [17]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py mr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[7108, 7109, 7110, 7111, 7112, 7113, 7114, 7115, 7116, 7117, 7118, 7119, 7120, 7121, 7122, 7123, 7124, 7125, 7126, 7127, 7128, 7129, 7130, 7131, 7132, 7133, 7134, 7135, 7136, 7137, 7138, 7139, 7140, 7141, 7142, 7143, 7144, 7145, 7146, 7147, 7148, 7149, 7150, 7151, 7152, 7153, 7154, 7155, 7156, 7157, 7158, 7159, 7160, 7161, 7162, 7163, 7164, 7165, 7166, 7167, 7168, 7169, 7170, 7171, 7172, 7173, 7174, 7175, 7176, 7177, 7178, 7179, 7180, 7181, 7182, 7183, 7184, 7185, 7186, 7187, 7188, 7189, 7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198, 7199, 7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209, 7210, 7211, 7212, 7213, 7214, 7215, 7216, 7217, 7218, 7219, 7220, 7221, 7222, 7223, 7224, 7225, 7226, 7227, 7228, 7229, 7230, 7231, 7232, 7233, 7234, 7235, 7236, 7237, 7238, 7239, 7240, 7241, 7242, 7243, 7244, 7245, 7246, 7247, 7248, 7249, 7250, 7251, 7252, 7253, 7254, 7255, 7256, 7257, 7258, 7259, 7260, 7261, 7262, 7263, 7264, 7265, 7266, 7267, 7268, 7269, 7270, 7271, 7272, 7273, 727

[[1 0]
 [0 1]
 [1 0]
 ...
 [1 0]
 [0 1]
 [1 0]]
[[0 1]
 [1 0]
 [0 1]
 ...
 [1 0]
 [0 1]
 [0 1]]
(6398, 300) (6398, 2) (3554, 300) (3554, 2) (25872, 300) (25872, 2)


In [10]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py cora

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]]
(1707, 300) (1707, 7) (812, 300) (812, 7) (3239, 300) (3239, 7)


In [11]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py pubmed

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[13802, 13803, 13804, 13805, 13806, 13807, 13808, 13809, 13810, 13811, 13812, 13813, 13814, 13815, 13816, 13817, 13818, 13819, 13820, 13821, 13822, 13823, 13824, 13825, 13826, 13827, 13828, 13829, 13830, 13831, 13832, 13833, 13834, 13835, 13836, 13837, 13838, 13839, 13840, 13841, 13842, 13843, 13844, 13845, 13846, 13847, 13848, 13849, 13850, 13851, 13852, 13853, 13854, 13855, 13856, 13857, 13858, 13859, 13860, 13861, 13862, 13863, 13864, 13865, 13866, 13867, 13868, 13869, 13870, 13871, 13872, 13873, 13874, 13875, 13876, 13877, 13878, 13879, 13880, 13881, 13882, 13883, 13884, 13885, 13886, 13887, 13888, 13889, 13890, 13891, 13892, 13893, 13894, 13895, 13896, 13897, 13898, 13899, 13900, 13901, 13902, 13903, 13904, 13905, 13906, 13907, 13908, 13909, 13910, 13911, 13912, 13913, 13914, 13915, 13916, 13917, 13918, 13919, 13920, 13921, 13922, 13923, 13924, 13925, 13926, 13927, 13928, 13929, 13930, 13931, 13932, 13933, 13934, 13935, 13936, 13937, 13938, 13939, 13940, 13941, 13942, 13943, 13944

[[1 0 0]
 [0 0 1]
 [0 0 1]
 ...
 [0 0 1]
 [1 0 0]
 [1 0 0]]
[[0 0 1]
 [0 0 1]
 [0 1 0]
 ...
 [0 0 1]
 [0 0 1]
 [0 0 1]]
(12422, 300) (12422, 3) (5915, 300) (5915, 3) (14254, 300) (14254, 3)


In [16]:
!../../gcn_text_categorization/venv/bin/python3 build_graph.py citeseer

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 248

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 ...
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[[0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 ...
 [0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]]
(2088, 300) (2088, 6) (993, 300) (993, 6) (5834, 300) (5834, 6)


In [8]:
!../../gcn_text_categorization/venv/bin/python3 train.py 20ng


(10183, 300) (10183, 20) (7532, 300) (7532, 20) (54071, 300) (54071, 20)
61603
  (0, 11321)	15.798612538007403
  (0, 11400)	2.133850774334169
  (0, 11438)	6.180494322637055
  (0, 11516)	7.136005767664492
  (0, 11614)	8.001111608570405
  (0, 11763)	19.99800641525627
  (0, 11779)	5.322267391717661
  (0, 11786)	6.288707907277288
  (0, 12052)	5.749711406544601
  (0, 12203)	2.2015318345337995
  (0, 12224)	14.129284638455148
  (0, 12267)	3.719372577872497
  (0, 12293)	41.665649694592524
  (0, 12310)	2.438560305567229
  (0, 12344)	6.05986633484844
  (0, 12433)	3.469031148938605
  (0, 12492)	9.765388473699547
  (0, 12528)	4.060230786436964
  (0, 12532)	4.401638258244908
  (0, 12596)	4.96885864556555
  (0, 12733)	5.526567855230391
  (0, 12740)	2.9939298026212007
  (0, 12798)	9.9377172911311
  (0, 12863)	4.346887743473499
  (0, 13059)	8.052296499538647
  :	:
  (61602, 46170)	3.8352427833241065
  (61602, 46187)	7.136005767664492
  (61602, 46579)	6.511851458591497
  (61602, 46595)	2.2567454627440

Epoch: 0019 train_loss= 1.80162 train_acc= 0.84975 val_loss= 1.75003 val_acc= 0.81609 time= 14.73961
Epoch: 0020 train_loss= 1.68385 train_acc= 0.86723 val_loss= 1.63602 val_acc= 0.83201 time= 14.78231
Epoch: 0021 train_loss= 1.56603 train_acc= 0.87931 val_loss= 1.52436 val_acc= 0.84439 time= 14.58428
Epoch: 0022 train_loss= 1.45136 train_acc= 0.88943 val_loss= 1.41667 val_acc= 0.84969 time= 14.82184
Epoch: 0023 train_loss= 1.34632 train_acc= 0.89385 val_loss= 1.31430 val_acc= 0.85234 time= 14.76146
Epoch: 0024 train_loss= 1.23676 train_acc= 0.89944 val_loss= 1.21846 val_acc= 0.85146 time= 14.59135
Epoch: 0025 train_loss= 1.14341 train_acc= 0.90376 val_loss= 1.12968 val_acc= 0.85676 time= 14.63439
Epoch: 0026 train_loss= 1.05386 train_acc= 0.90740 val_loss= 1.04851 val_acc= 0.86030 time= 14.85966
Epoch: 0027 train_loss= 0.96948 train_acc= 0.90809 val_loss= 0.97498 val_acc= 0.86295 time= 14.54689
Epoch: 0028 train_loss= 0.89270 train_acc= 0.90936 val_loss= 0.90880 val_acc= 0.86472 time=

(0.8617896972915561, 0.8617896972915561, 0.8617896972915561, None)
embeddings:
42757 11314 7532
[[ 0.16008577 -0.11579843  0.09027    ... -0.09364252  0.64616114
   0.45087463]
 [ 0.19507906  0.24837592  0.1632822  ...  0.09942342  0.53346163
   0.17832536]
 [ 0.07010279  0.07506197  0.23644076 ...  0.03230935  0.29313472
   0.25861096]
 ...
 [ 0.20336048  0.24373874  0.34451702 ...  0.3076356   0.13262486
   0.16502395]
 [ 0.27521408  0.35767594  0.0769699  ...  0.08596726  0.18843639
   0.2865709 ]
 [-0.0053094   0.06484845  0.01448505 ...  0.26763478  0.21925645
   0.01504545]]


In [11]:
!../../gcn_text_categorization/venv/bin/python3 train.py R8


(4937, 300) (4937, 8) (2189, 300) (2189, 8) (13173, 300) (13173, 8)
15362
  (0, 5850)	0.09164216929228669
  (0, 6006)	5.138930781036578
  (0, 6066)	2.208626312805042
  (0, 6089)	5.825014098016193
  (0, 6739)	4.514776471963584
  (0, 6848)	6.001154291640457
  (0, 7342)	2.987168577777116
  (0, 7392)	14.707626008917043
  (0, 7728)	4.402298488536894
  (0, 8623)	1.8219204856022904
  (0, 8787)	3.3696441676605815
  (0, 9159)	6.866151729127062
  (0, 9515)	3.2318604652975287
  (0, 9576)	4.218205452094557
  (0, 9829)	0.6051372578907143
  (0, 10086)	5.074392259899007
  (0, 10291)	4.291632920649374
  (0, 10494)	2.9768857108215316
  (0, 10665)	13.286016355625703
  (0, 10905)	4.851248708584797
  (0, 11319)	4.5267526630103
  (0, 11378)	7.559298909687007
  (0, 11394)	9.152290836679752
  (0, 11640)	1.9957368158061253
  (0, 11955)	4.851248708584797
  :	:
  (15360, 8563)	1.1979964321140117
  (15360, 9172)	4.628105157270587
  (15360, 9303)	1.3204861225679978
  (15360, 9352)	5.721976505726523
  (15360, 936

Epoch: 0020 train_loss= 0.63982 train_acc= 0.79583 val_loss= 0.59358 val_acc= 0.81752 time= 1.24341
Epoch: 0021 train_loss= 0.61934 train_acc= 0.81122 val_loss= 0.56960 val_acc= 0.83577 time= 1.19242
Epoch: 0022 train_loss= 0.59288 train_acc= 0.83006 val_loss= 0.54539 val_acc= 0.84854 time= 1.15094
Epoch: 0023 train_loss= 0.57138 train_acc= 0.84181 val_loss= 0.52106 val_acc= 0.86679 time= 1.22460
Epoch: 0024 train_loss= 0.54501 train_acc= 0.85821 val_loss= 0.49698 val_acc= 0.87044 time= 1.15970
Epoch: 0025 train_loss= 0.51859 train_acc= 0.86591 val_loss= 0.47355 val_acc= 0.87956 time= 1.26263
Epoch: 0026 train_loss= 0.49715 train_acc= 0.87097 val_loss= 0.45120 val_acc= 0.87956 time= 1.19651
Epoch: 0027 train_loss= 0.47464 train_acc= 0.87604 val_loss= 0.43016 val_acc= 0.88139 time= 1.26420
Epoch: 0028 train_loss= 0.45576 train_acc= 0.88070 val_loss= 0.41049 val_acc= 0.88686 time= 1.31731
Epoch: 0029 train_loss= 0.43468 train_acc= 0.88738 val_loss= 0.39208 val_acc= 0.89051 time= 1.16741


In [18]:
!../../gcn_text_categorization/venv/bin/python3 train.py R52


(5879, 300) (5879, 52) (2568, 300) (2568, 52) (15424, 300) (15424, 52)
17992
  (0, 6580)	13.456407118768809
  (0, 6652)	11.991729977854375
  (0, 7667)	10.338446308573266
  (0, 7802)	3.5476851887438445
  (0, 8070)	2.9783026384187075
  (0, 8081)	5.149999386630077
  (0, 8954)	1.8604384182512763
  (0, 8984)	1.1093288470645744
  (0, 10428)	6.256212330425571
  (0, 10430)	4.853349815463626
  (0, 10833)	4.059783887156633
  (0, 10907)	5.560681631015528
  (0, 10982)	2.889493023217476
  (0, 11702)	3.2439119030295256
  (0, 12074)	0.5254001830155217
  (0, 12903)	18.92947997356531
  (0, 13058)	19.318781322291557
  (0, 13801)	0.09818243264420962
  (0, 13872)	3.536299866518719
  (0, 13923)	4.452590598392875
  (0, 14018)	3.02851632033319
  (0, 15067)	3.934246142212856
  (1, 7033)	2.115695232229711
  (1, 7151)	1.3415941822019837
  (1, 7161)	3.7133523106326622
  :	:
  (17990, 12569)	7.453915925376881
  (17990, 13459)	4.424681810275798
  (17990, 13801)	0.09818243264420962
  (17990, 13922)	4.9113370731139

Epoch: 0019 train_loss= 1.67137 train_acc= 0.65317 val_loss= 1.69544 val_acc= 0.64012 time= 1.70759
Epoch: 0020 train_loss= 1.60844 train_acc= 0.66083 val_loss= 1.64249 val_acc= 0.65084 time= 1.72567
Epoch: 0021 train_loss= 1.55369 train_acc= 0.66219 val_loss= 1.59009 val_acc= 0.65084 time= 1.67091
Epoch: 0022 train_loss= 1.49749 train_acc= 0.66559 val_loss= 1.53851 val_acc= 0.65084 time= 1.80530
Epoch: 0023 train_loss= 1.44557 train_acc= 0.66746 val_loss= 1.48926 val_acc= 0.65850 time= 1.76054
Epoch: 0024 train_loss= 1.39877 train_acc= 0.66882 val_loss= 1.44332 val_acc= 0.67228 time= 1.77637
Epoch: 0025 train_loss= 1.34875 train_acc= 0.68107 val_loss= 1.40086 val_acc= 0.68453 time= 1.63961
Epoch: 0026 train_loss= 1.30790 train_acc= 0.69280 val_loss= 1.36161 val_acc= 0.69066 time= 1.75588
Epoch: 0027 train_loss= 1.27186 train_acc= 0.70471 val_loss= 1.32507 val_acc= 0.70444 time= 1.71154
Epoch: 0028 train_loss= 1.23388 train_acc= 0.71475 val_loss= 1.29083 val_acc= 0.71976 time= 1.64881


Epoch: 0101 train_loss= 0.15650 train_acc= 0.96734 val_loss= 0.30558 val_acc= 0.92037 time= 1.74513
Epoch: 0102 train_loss= 0.15042 train_acc= 0.97058 val_loss= 0.30396 val_acc= 0.92190 time= 1.73584
Epoch: 0103 train_loss= 0.14754 train_acc= 0.97194 val_loss= 0.30311 val_acc= 0.92190 time= 1.71295
Epoch: 0104 train_loss= 0.14565 train_acc= 0.96717 val_loss= 0.30067 val_acc= 0.92190 time= 1.75773
Epoch: 0105 train_loss= 0.14251 train_acc= 0.97330 val_loss= 0.29805 val_acc= 0.92343 time= 1.77230
Epoch: 0106 train_loss= 0.13646 train_acc= 0.97279 val_loss= 0.29424 val_acc= 0.92496 time= 1.78205
Epoch: 0107 train_loss= 0.13481 train_acc= 0.97466 val_loss= 0.28964 val_acc= 0.92649 time= 1.76968
Epoch: 0108 train_loss= 0.12813 train_acc= 0.97500 val_loss= 0.28654 val_acc= 0.92496 time= 1.61189
Epoch: 0109 train_loss= 0.13046 train_acc= 0.97483 val_loss= 0.28471 val_acc= 0.92343 time= 1.70802
Epoch: 0110 train_loss= 0.12636 train_acc= 0.97449 val_loss= 0.28254 val_acc= 0.92496 time= 1.68202


In [19]:
!../../gcn_text_categorization/venv/bin/python3 train.py ohsumed


(3022, 300) (3022, 23) (4043, 300) (4043, 23) (17514, 300) (17514, 23)
21557
  (0, 3374)	9.379455148032308
  (0, 3385)	4.376635786039005
  (0, 3563)	15.541419033383939
  (0, 3571)	5.8647128414688385
  (0, 3581)	5.613398413187932
  (0, 3996)	5.3828747545760995
  (0, 4021)	3.014787400896863
  (0, 4213)	3.30711645831256
  (0, 4761)	9.663395670573083
  (0, 5021)	3.6888794541139363
  (0, 5234)	3.1630320886521077
  (0, 5450)	4.920251232627987
  (0, 5587)	1.7058297581091664
  (0, 5794)	4.848792268645842
  (0, 5880)	1.3702082233682662
  (0, 6358)	3.9819815940350565
  (0, 6531)	5.651138741170779
  (0, 6844)	4.344887087724425
  (0, 6849)	4.591747165655951
  (0, 6907)	0.6513854144689795
  (0, 7075)	5.353887217702847
  (0, 7337)	2.0115303360636254
  (0, 7476)	3.1192751082950076
  (0, 7616)	19.272985888212784
  (0, 7868)	2.0309088109009363
  :	:
  (21556, 12065)	6.775548722660029
  (21556, 12451)	2.56711386047111
  (21556, 12501)	1.2937971852416479
  (21556, 12605)	16.622580352343586
  (21556, 126

Epoch: 0020 train_loss= 2.37064 train_acc= 0.34150 val_loss= 2.38253 val_acc= 0.30746 time= 3.46632
Epoch: 0021 train_loss= 2.32383 train_acc= 0.35407 val_loss= 2.34119 val_acc= 0.31642 time= 3.44821
Epoch: 0022 train_loss= 2.27366 train_acc= 0.36698 val_loss= 2.29858 val_acc= 0.31940 time= 3.45449
Epoch: 0023 train_loss= 2.22462 train_acc= 0.36764 val_loss= 2.25511 val_acc= 0.32537 time= 3.48736
Epoch: 0024 train_loss= 2.17525 train_acc= 0.37922 val_loss= 2.21063 val_acc= 0.33433 time= 3.52926
Epoch: 0025 train_loss= 2.12411 train_acc= 0.39709 val_loss= 2.16503 val_acc= 0.35821 time= 3.49771
Epoch: 0026 train_loss= 2.07366 train_acc= 0.41694 val_loss= 2.11856 val_acc= 0.37612 time= 3.38111
Epoch: 0027 train_loss= 2.02002 train_acc= 0.45268 val_loss= 2.07166 val_acc= 0.41194 time= 3.48099
Epoch: 0028 train_loss= 1.96327 train_acc= 0.48511 val_loss= 2.02519 val_acc= 0.45373 time= 3.59396
Epoch: 0029 train_loss= 1.90429 train_acc= 0.52945 val_loss= 1.97936 val_acc= 0.50149 time= 3.59579


(0.6740303614329115, 0.603667329156348, 0.6267926729349171, None)
Micro average Test Precision, Recall and F1-Score...
(0.6866188473905516, 0.6866188473905516, 0.6866188473905516, None)
embeddings:
14157 3357 4043
[[ 1.48497403e-01  3.75817090e-01  2.76928395e-01 ...  1.04703315e-01
   1.07515961e-01  6.87675998e-02]
 [ 2.84891933e-01 -3.45522538e-04  3.21059376e-01 ... -4.72546974e-03
   5.67395501e-02 -5.83318770e-02]
 [ 1.81133613e-01  2.83373326e-01  2.14034438e-01 ...  6.64357245e-02
   2.03806296e-01  1.28948987e-01]
 ...
 [ 1.26385361e-01  5.07476032e-02 -1.87976137e-02 ...  3.32719646e-02
   3.60627651e-01  1.62102103e-01]
 [ 1.14408419e-01  3.63545060e-01  1.58303499e-01 ...  1.50323808e-01
   2.01016158e-01  2.76916087e-01]
 [ 1.21680796e-01  2.33633369e-01  2.20138803e-01 ...  7.90198967e-02
   2.41784975e-01  2.81558871e-01]]


In [20]:
!../../gcn_text_categorization/venv/bin/python3 train.py mr


(6398, 300) (6398, 2) (3554, 300) (3554, 2) (25872, 300) (25872, 2)
29426
  (0, 7493)	1.0930021499776208
  (0, 7933)	3.2270691183364284
  (0, 8340)	7.888146936262816
  (0, 9113)	0.5557777303337534
  (0, 10185)	4.555942426087611
  (0, 11090)	1.8885902192574975
  (0, 11991)	7.888146936262816
  (0, 12139)	3.0053450136764446
  (0, 13969)	8.175829008714597
  (0, 14248)	6.501852575142925
  (0, 15138)	6.9718562043886605
  (0, 15519)	5.10005402748707
  (0, 16232)	7.19499975570287
  (0, 16250)	2.6978446351915606
  (0, 16416)	7.328531148327393
  (0, 17940)	4.2118462643557395
  (0, 17947)	3.793802374040715
  (0, 18519)	2.1229558334779712
  (0, 18839)	8.175829008714597
  (0, 19460)	2.090570582320254
  (0, 20045)	2.8511943338491865
  (0, 20725)	5.777933735916226
  (0, 22000)	3.258284137684353
  (0, 22435)	2.802095002881806
  (0, 23019)	8.175829008714597
  :	:
  (29424, 20424)	5.513241181689144
  (29424, 21467)	6.138947081453557
  (29424, 22309)	6.6353839677674475
  (29424, 22939)	1.500846830022512

Epoch: 0019 train_loss= 0.20227 train_acc= 0.93014 val_loss= 0.51995 val_acc= 0.76620 time= 0.85878
Early stopping...
Optimization Finished!
Test set results: cost= 0.54154 accuracy= 0.76928 time= 0.28843
29426
Test Precision, Recall and F1-Score...
              precision    recall  f1-score   support

           0     0.7806    0.7490    0.7645      1777
           1     0.7588    0.7895    0.7739      1777

    accuracy                         0.7693      3554
   macro avg     0.7697    0.7693    0.7692      3554
weighted avg     0.7697    0.7693    0.7692      3554

Macro average Test Precision, Recall and F1-Score...
(0.7697168478166053, 0.7692740574001126, 0.7691793236225828, None)
Micro average Test Precision, Recall and F1-Score...
(0.7692740574001126, 0.7692740574001126, 0.7692740574001126, None)
embeddings:
18764 7108 3554
[[-0.01984934 -0.00484938 -0.00762159 ...  0.12973008 -0.0246121
  -0.02190567]
 [ 0.02179906 -0.00807534  0.01198137 ...  0.12855463  0.00708571
   0.0091

In [17]:
!../../gcn_text_categorization/venv/bin/python3 train.py cora

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0042 train_loss= 0.47807 train_acc= 0.85589 val_loss= 0.67373 val_acc= 0.76720 time= 0.37112
Epoch: 0043 train_loss= 0.45973 train_acc= 0.86467 val_loss= 0.66637 val_acc= 0.76190 time= 0.36949
Epoch: 0044 train_loss= 0.44144 train_acc= 0.86878 val_loss= 0.66290 val_acc= 0.78307 time= 0.37582
Epoch: 0045 train_loss= 0.42467 train_acc= 0.87346 val_loss= 0.65771 val_acc= 0.78307 time= 0.36717
Epoch: 0046 train_loss= 0.42109 train_acc= 0.87053 val_loss= 0.65137 val_acc= 0.78307 time= 0.35253
Epoch: 0047 train_loss= 0.40115 train_acc= 0.87991 val_loss= 0.64637 val_acc= 0.77249 time= 0.36873
Epoch: 0048 train_loss= 0.38905 train_acc= 0.88459 val_loss= 0.64331 val_acc= 0.77249 time= 0.38838
Epoch: 0049 train_loss= 0.37776 train_acc= 0.87932 val_loss= 0.64146 val_acc= 0.78307 time= 0.35720
Epoch: 0050 train_loss= 0.35938 train_acc= 0.88752 val_loss= 0.63979 val_acc= 0.78307 time= 0.38287
Epoch: 0051 train_loss= 0.34673 train_acc= 0.89572 val_loss= 0.63976 val_acc= 0.76720 time= 0.36940


In [18]:
!../../gcn_text_categorization/venv/bin/python3 train.py pubmed

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0041 train_loss= 0.43874 train_acc= 0.82295 val_loss= 0.42444 val_acc= 0.82971 time= 1.70146
Epoch: 0042 train_loss= 0.43389 train_acc= 0.82480 val_loss= 0.41965 val_acc= 0.83333 time= 1.71940
Epoch: 0043 train_loss= 0.42411 train_acc= 0.83188 val_loss= 0.42010 val_acc= 0.82754 time= 1.70436
Epoch: 0044 train_loss= 0.42691 train_acc= 0.82770 val_loss= 0.41171 val_acc= 0.83116 time= 1.68186
Epoch: 0045 train_loss= 0.41503 train_acc= 0.83446 val_loss= 0.41203 val_acc= 0.83333 time= 1.69055
Epoch: 0046 train_loss= 0.42676 train_acc= 0.82818 val_loss= 0.40637 val_acc= 0.83478 time= 1.69416
Epoch: 0047 train_loss= 0.41486 train_acc= 0.83325 val_loss= 0.40359 val_acc= 0.83261 time= 1.67750
Epoch: 0048 train_loss= 0.41313 train_acc= 0.83397 val_loss= 0.39945 val_acc= 0.84203 time= 1.64144
Epoch: 0049 train_loss= 0.40393 train_acc= 0.83744 val_loss= 0.40175 val_acc= 0.84420 time= 1.69128
Epoch: 0050 train_loss= 0.41304 train_acc= 0.83502 val_loss= 0.39422 val_acc= 0.84275 time= 1.66827


In [19]:
!../../gcn_text_categorization/venv/bin/python3 train.py citeseer

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0042 train_loss= 0.46815 train_acc= 0.84339 val_loss= 0.76384 val_acc= 0.75758 time= 1.07447
Epoch: 0043 train_loss= 0.45345 train_acc= 0.85201 val_loss= 0.77559 val_acc= 0.75758 time= 1.07848
Epoch: 0044 train_loss= 0.43370 train_acc= 0.86399 val_loss= 0.79149 val_acc= 0.75758 time= 1.10996
Early stopping...
Optimization Finished!
Test set results: cost= 0.83786 accuracy= 0.73212 time= 0.23052
6827
Test Precision, Recall and F1-Score...
              precision    recall  f1-score   support

           0     0.7157    0.6912    0.7032       204
           1     0.7273    0.7619    0.7442       189
           2     0.7804    0.8029    0.7915       208
           3     0.5208    0.3623    0.4274        69
           4     0.7222    0.7800    0.7500       150
           5     0.7644    0.7688    0.7666       173

    accuracy                         0.7321       993
   macro avg     0.7051    0.6945    0.6971       993
weighted avg     0.7274    0.7321    0.7284       993

Macro av