In [1]:
%cd /4tb/nabarun/nlp/text_gcn

/4tb/nabarun/nlp/text_gcn


In [2]:
!ls

bow.py		 inits.py      plot_window.py	train.py
build_corpus.py  layers.py     prepare_data.py	utils.py
build_graph.py	 metrics.py    __pycache__	visualize.py
data		 models.py     README.md	visualize_words.py
doc2vec.py	 plot_dim.py   remove_words.py	wordnet.py
__init__.py	 plot_prop.py  results


In [3]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py 20ng

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'for', 'those', 'won', 'hers', 'its', "she's", 'is', 'being', "aren't", 'same', 'through', 'below', 'a', 'ain', 'here', "doesn't", 'that', 'aren', 'own', 'all', "mightn't", 'were', 'was', 'during', 'can', 'him', 'o', 'than', 'them', 'have', 'did', 'haven', 'doesn', 'then', "wouldn't", 'll', 'on', "wasn't", 'after', 'mightn', 'this', 'shan', 'again', "weren't", "you've", "couldn't", 'theirs', 'further', 't', 'where', 'hasn', 'didn', 'with', 'most', 'itself', 'weren', 'should', 'hadn', 'yourself', 'whom', 'me', "you'll", 're', 'but', 'until', 'will', 'our', 'now', 'under', 'mustn', 'had', 'they', 'herself', 'be', "haven't", "hasn't", 'what', 'each', 'we', 'himself', 'an', 'between', 'before', "should've", 'she', "shouldn't", 'or', 'am', 'the', 'down', 'ourselves', 'how', 'your', 'needn', 'these', 'ma', 'up', 'themselves', 'so', 'doing', 'against'

In [4]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py R8

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'re', 'hadn', 'any', 'mightn', 'up', 'all', 'ma', 'has', 'isn', "aren't", 'between', 'don', 'both', 'if', 'then', 'couldn', 'do', "mightn't", 'over', 'from', 'my', 'during', 'these', "should've", "mustn't", 'o', "she's", 'yourselves', 'won', 'very', 'am', 'an', 'here', 'such', 'same', 'yours', 'or', 'ours', 'was', 'now', 'than', "wasn't", "you've", 'yourself', "won't", 'himself', 'because', "didn't", 'he', 'but', 'as', 'our', 'before', 'once', 'that', 'so', 'where', 'they', 'why', 'him', "haven't", 'shouldn', 'to', "wouldn't", 'of', 'again', "don't", 'you', 'nor', 'above', 'wasn', 'at', 's', 'haven', "hadn't", 'i', "you're", 'does', 'their', 'hers', 'down', 'weren', 'hasn', 'below', 'doing', 'for', 'being', "you'd", 'and', 'y', 'who', 'which', 'itself', "shan't", 'theirs', 't', 'more', 'did', 'about', "doesn't", 'how', 'most', 'further', 'while

In [5]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py R52

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{"doesn't", 'shan', 'at', 'they', 'and', 'doing', 'once', 'that', 'other', 'll', "you're", 'there', 'themselves', "she's", 'wasn', 'a', 'itself', "needn't", 'on', 'because', 'had', 'no', 'yourselves', 'above', "mustn't", 'an', 'what', 'each', 'them', 'into', 'this', 'haven', 'doesn', 'won', 'for', 'are', 'same', 'which', 'how', 'your', 'was', 'do', 'd', "hasn't", 'by', 'both', 'she', 'off', 'ours', 'until', 'does', 'am', 'should', 'needn', 'whom', 'yours', 'm', "wasn't", 'isn', 'himself', "should've", 'to', 've', "shan't", 'ourselves', 'as', 'having', 'here', "aren't", 'any', 'theirs', "wouldn't", "hadn't", 'hadn', 'or', 'who', 'didn', 'have', 'out', 'been', 'mustn', 'yourself', 'down', 'then', 'ma', 'further', 'these', 'wouldn', 'when', 'only', 'such', 'too', "you'll", 'under', 'mightn', 'we', 'i', 'again', 'very', 'those', "weren't", 'be', "it

In [6]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py ohsumed

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'his', 'needn', 'there', 'under', 'hadn', "wasn't", 'that', 'such', "you're", 'why', 'hasn', 'yourselves', 'as', 'now', 'shan', 'about', "needn't", 'did', 'will', 'all', "mightn't", 'be', 'themselves', 'he', "you've", 'won', 'she', 'their', 'does', 'me', 'than', 'then', 'some', 'few', 're', 'nor', 'ma', 'i', 'when', 'but', 'its', 'the', 'can', 'they', 't', 'd', "it's", 'out', 'below', 'up', 'aren', 'didn', 'to', "shan't", 'a', 'was', 'isn', "weren't", 'herself', 'll', "should've", 'yours', 'it', 'further', 'while', 'my', 'ourselves', 'y', 'because', 'an', 'from', 'just', "haven't", 'itself', 'theirs', 'before', 'until', 'on', 'after', 'm', 'over', 'more', 'had', 'again', "doesn't", 'having', 'other', 'our', 'hers', 'have', "mustn't", "she's", 'at', "didn't", 'him', 'mustn', "wouldn't", 'own', "hadn't", 'am', 'do', 'ain', 'how', "won't", 'myself

In [7]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py mr

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'haven', 'that', 'themselves', 'isn', 'aren', "mightn't", "you'll", 'he', 'while', 'ain', 'was', 'through', 'up', 'no', 'what', "you'd", 'just', 'my', 'i', 'where', 'very', "aren't", 'and', "it's", 'is', 'm', 'to', 'didn', "doesn't", 'hadn', 'mustn', 'for', 'all', 'myself', 'can', 'hers', 'will', 'we', 'down', 'should', 'wasn', 'some', 'out', 'theirs', 'there', "couldn't", 'her', 'these', "needn't", 'from', 'hasn', 'doesn', 'nor', 'himself', 'during', "should've", 'shouldn', 'be', 'our', 'of', "isn't", 'this', "you're", 'yourselves', 'whom', 'couldn', 'weren', 'until', "hasn't", 'because', 'with', 'over', 'ours', 't', 'do', 'between', 'so', 'those', 'about', 'too', 'mightn', 'each', "she's", 'against', 'have', "won't", 'she', 'herself', "mustn't", 'other', 'on', 'or', 'under', 'at', 'into', 'then', "wouldn't", 'both', "shouldn't", 'their', 'bei

In [8]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py cora

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{"doesn't", 'until', 'couldn', 'who', 'there', 'too', 'now', 'or', 'didn', 'haven', 'during', 'been', 'its', 'ours', 'very', 'your', 'into', 'what', 'were', 'aren', 'yours', 're', 'did', 'in', 'yourselves', 'herself', 'and', 'we', 'himself', 'why', 'more', 'shouldn', "aren't", "weren't", 'their', 'them', 'i', 'my', 'which', 'for', "shan't", 'hasn', 'they', 'where', 'the', 'under', 'he', 'it', 'so', 'mustn', 'that', 'of', 'other', 'most', 'how', 'll', "couldn't", 'these', 'should', 'yourself', "isn't", 'down', 'if', 'itself', 'don', 'then', "you'd", 'few', "haven't", 'o', 'before', 'but', 'whom', "should've", 's', 'will', "shouldn't", "wouldn't", "you'll", "you've", 'after', 'themselves', 'from', 'an', 'being', 'any', 'out', "wasn't", 've', 'isn', "you're", 'both', 'his', 'theirs', 'above', 'our', 'not', "mightn't", 'by', 'further', 'me', 'be', '

In [9]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py pubmed

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'yours', 'just', 'my', 'if', 'what', 'its', 'shouldn', 'ourselves', 'hadn', 'can', "shan't", 'yourself', 'you', 'any', 'weren', 'this', 'whom', 'with', "you've", 's', 'has', "you're", 'such', 'during', 'same', 'her', 't', 'your', 'who', 'out', 'a', 'all', 'over', "mightn't", 'll', "it's", "wouldn't", 'isn', 'from', 'until', 'only', "shouldn't", 'in', "hadn't", 'too', 'how', "you'd", "aren't", 'those', 'down', "hasn't", 'shan', 'both', 'of', 'there', 'each', 'needn', 'before', 'didn', 'nor', 'between', 'up', 'own', 'an', 'or', 'below', 'does', 'should', 'be', "needn't", 'theirs', 'having', 'do', 'himself', 'his', 'is', 'couldn', 'as', 'aren', 'while', 'haven', 'very', "don't", 'under', 'won', 'i', 'that', "mustn't", 'was', 'about', "didn't", 'we', 'have', 'will', 'against', 'above', 'at', 'them', 'm', "won't", 'but', 'are', "should've", 'the', '

In [10]:
!../gcn_text_categorization/venv/bin/python3 remove_words.py citeseer

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/nabarun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'those', "isn't", 'shouldn', 'she', "haven't", "you're", "that'll", 'through', 'if', "she's", 'themselves', 'you', 'before', 'further', 'how', 'wasn', 'now', "mightn't", 'ourselves', 'both', 's', 'from', 'is', 'ain', 'me', "hadn't", 'this', 'with', 'after', 're', 'these', "weren't", 'has', "hasn't", 'do', 'mightn', 'there', 'each', "wasn't", 'weren', 'until', "it's", 'a', 'below', 'such', 'our', "shouldn't", 'who', 'ma', 'which', 'to', "couldn't", 'we', 'because', 'had', 'their', 'the', 'doesn', 'll', 'on', 'off', 'for', 'no', 'most', "shan't", 'all', 'him', 'nor', 't', 'yours', 'while', 'did', 'up', 'that', 'isn', 'm', "mustn't", 'your', 'having', 'have', "you've", 'why', 'hers', 'by', 'as', 'down', 'too', 've', 'against', 'then', 'or', 'wouldn', 'needn', 'into', 'hasn', "you'd", "won't", 'its', 'won', 'what', 'don', 'over', 'should', 'own', '

In [11]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py 20ng

Loaded Word Vectors!
[7532, 7533, 7534, 7535, 7536, 7537, 7538, 7539, 7540, 7541, 7542, 7543, 7544, 7545, 7546, 7547, 7548, 7549, 7550, 7551, 7552, 7553, 7554, 7555, 7556, 7557, 7558, 7559, 7560, 7561, 7562, 7563, 7564, 7565, 7566, 7567, 7568, 7569, 7570, 7571, 7572, 7573, 7574, 7575, 7576, 7577, 7578, 7579, 7580, 7581, 7582, 7583, 7584, 7585, 7586, 7587, 7588, 7589, 7590, 7591, 7592, 7593, 7594, 7595, 7596, 7597, 7598, 7599, 7600, 7601, 7602, 7603, 7604, 7605, 7606, 7607, 7608, 7609, 7610, 7611, 7612, 7613, 7614, 7615, 7616, 7617, 7618, 7619, 7620, 7621, 7622, 7623, 7624, 7625, 7626, 7627, 7628, 7629, 7630, 7631, 7632, 7633, 7634, 7635, 7636, 7637, 7638, 7639, 7640, 7641, 7642, 7643, 7644, 7645, 7646, 7647, 7648, 7649, 7650, 7651, 7652, 7653, 7654, 7655, 7656, 7657, 7658, 7659, 7660, 7661, 7662, 7663, 7664, 7665, 7666, 7667, 7668, 7669, 7670, 7671, 7672, 7673, 7674, 7675, 7676, 7677, 7678, 7679, 7680, 7681, 7682, 7683, 7684, 7685, 7686, 7687, 7688, 7689, 7690, 7691, 7692, 7693, 7694, 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
(10183, 300) (10183, 20) (7532, 300) (7532, 20) (54071, 300) (54071, 20)


In [12]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py R8

Loaded Word Vectors!
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217

[5485, 5486, 5487, 5488, 5489, 5490, 5491, 5492, 5493, 5494, 5495, 5496, 5497, 5498, 5499, 5500, 5501, 5502, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518, 5519, 5520, 5521, 5522, 5523, 5524, 5525, 5526, 5527, 5528, 5529, 5530, 5531, 5532, 5533, 5534, 5535, 5536, 5537, 5538, 5539, 5540, 5541, 5542, 5543, 5544, 5545, 5546, 5547, 5548, 5549, 5550, 5551, 5552, 5553, 5554, 5555, 5556, 5557, 5558, 5559, 5560, 5561, 5562, 5563, 5564, 5565, 5566, 5567, 5568, 5569, 5570, 5571, 5572, 5573, 5574, 5575, 5576, 5577, 5578, 5579, 5580, 5581, 5582, 5583, 5584, 5585, 5586, 5587, 5588, 5589, 5590, 5591, 5592, 5593, 5594, 5595, 5596, 5597, 5598, 5599, 5600, 5601, 5602, 5603, 5604, 5605, 5606, 5607, 5608, 5609, 5610, 5611, 5612, 5613, 5614, 5615, 5616, 5617, 5618, 5619, 5620, 5621, 5622, 5623, 5624, 5625, 5626, 5627, 5628, 5629, 5630, 5631, 5632, 5633, 5634, 5635, 5636, 5637, 5638, 5639, 5640, 5641, 5642, 5643, 5644, 5645, 5646, 5647, 5648, 5649, 5650, 565

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]
(4937, 300) (4937, 8) (2189, 300) (2189, 8) (13173, 300) (13173, 8)


In [13]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py R52

Loaded Word Vectors!
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217

[6532, 6533, 6534, 6535, 6536, 6537, 6538, 6539, 6540, 6541, 6542, 6543, 6544, 6545, 6546, 6547, 6548, 6549, 6550, 6551, 6552, 6553, 6554, 6555, 6556, 6557, 6558, 6559, 6560, 6561, 6562, 6563, 6564, 6565, 6566, 6567, 6568, 6569, 6570, 6571, 6572, 6573, 6574, 6575, 6576, 6577, 6578, 6579, 6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588, 6589, 6590, 6591, 6592, 6593, 6594, 6595, 6596, 6597, 6598, 6599, 6600, 6601, 6602, 6603, 6604, 6605, 6606, 6607, 6608, 6609, 6610, 6611, 6612, 6613, 6614, 6615, 6616, 6617, 6618, 6619, 6620, 6621, 6622, 6623, 6624, 6625, 6626, 6627, 6628, 6629, 6630, 6631, 6632, 6633, 6634, 6635, 6636, 6637, 6638, 6639, 6640, 6641, 6642, 6643, 6644, 6645, 6646, 6647, 6648, 6649, 6650, 6651, 6652, 6653, 6654, 6655, 6656, 6657, 6658, 6659, 6660, 6661, 6662, 6663, 6664, 6665, 6666, 6667, 6668, 6669, 6670, 6671, 6672, 6673, 6674, 6675, 6676, 6677, 6678, 6679, 6680, 6681, 6682, 6683, 6684, 6685, 6686, 6687, 6688, 6689, 6690, 6691, 6692, 6693, 6694, 6695, 6696, 6697, 669

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(5879, 300) (5879, 52) (2568, 300) (2568, 52) (15424, 300) (15424, 52)


In [14]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py ohsumed

Loaded Word Vectors!
[4043, 4044, 4045, 4046, 4047, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4056, 4057, 4058, 4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4067, 4068, 4069, 4070, 4071, 4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079, 4080, 4081, 4082, 4083, 4084, 4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108, 4109, 4110, 4111, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136, 4137, 4138, 4139, 4140, 4141, 4142, 4143, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4157, 4158, 4159, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4168, 4169, 4170, 4171, 4172, 4173, 4174, 4175, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4200, 4201, 4202, 4203, 4204, 4205, 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(3022, 300) (3022, 23) (4043, 300) (4043, 23) (17514, 300) (17514, 23)


In [15]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py mr

Loaded Word Vectors!
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217

[7108, 7109, 7110, 7111, 7112, 7113, 7114, 7115, 7116, 7117, 7118, 7119, 7120, 7121, 7122, 7123, 7124, 7125, 7126, 7127, 7128, 7129, 7130, 7131, 7132, 7133, 7134, 7135, 7136, 7137, 7138, 7139, 7140, 7141, 7142, 7143, 7144, 7145, 7146, 7147, 7148, 7149, 7150, 7151, 7152, 7153, 7154, 7155, 7156, 7157, 7158, 7159, 7160, 7161, 7162, 7163, 7164, 7165, 7166, 7167, 7168, 7169, 7170, 7171, 7172, 7173, 7174, 7175, 7176, 7177, 7178, 7179, 7180, 7181, 7182, 7183, 7184, 7185, 7186, 7187, 7188, 7189, 7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198, 7199, 7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209, 7210, 7211, 7212, 7213, 7214, 7215, 7216, 7217, 7218, 7219, 7220, 7221, 7222, 7223, 7224, 7225, 7226, 7227, 7228, 7229, 7230, 7231, 7232, 7233, 7234, 7235, 7236, 7237, 7238, 7239, 7240, 7241, 7242, 7243, 7244, 7245, 7246, 7247, 7248, 7249, 7250, 7251, 7252, 7253, 7254, 7255, 7256, 7257, 7258, 7259, 7260, 7261, 7262, 7263, 7264, 7265, 7266, 7267, 7268, 7269, 7270, 7271, 7272, 7273, 727

[7069, 6507, 3196, 3960, 3243, 351, 589, 4854, 5905, 7084, 220, 320, 4392, 2161, 2800, 4094, 5509, 5239, 2728, 3157, 3065, 2112, 1101, 3543, 4867, 2706, 1472, 6875, 292, 4791, 3919, 4155, 1474, 2600, 4560, 6678, 1672, 556, 280, 2335, 3077, 5433, 281, 6824, 902, 4256, 2623, 1657, 2187, 6808, 1054, 2669, 1151, 709, 3044, 2251, 2344, 4785, 5321, 5647, 1266, 7063, 6716, 6887, 2851, 1519, 6572, 3674, 4799, 6567, 2127, 285, 4334, 2960, 3677, 5379, 5425, 5018, 5307, 1166, 3790, 2120, 6600, 1184, 6542, 659, 6759, 4266, 3602, 1152, 3084, 5618, 1099, 4760, 1586, 5183, 5598, 527, 811, 3909, 6387, 5557, 1538, 1111, 3087, 4083, 2446, 6415, 2631, 4835, 3597, 1163, 1158, 5473, 972, 7047, 3183, 774, 494, 6224, 2052, 6921, 2138, 4602, 550, 5941, 480, 2953, 6890, 3497, 4453, 2213, 425, 5267, 2979, 5001, 3354, 6065, 2230, 2815, 549, 1368, 6898, 3546, 4099, 2196, 4177, 7035, 1609, 7044, 4035, 6958, 544, 4965, 2058, 6442, 6692, 3951, 4995, 3655, 85, 5975, 1605, 5175, 4451, 2877, 1129, 4834, 6607, 6530, 463

[[0 1]
 [0 1]
 [1 0]
 ...
 [1 0]
 [0 1]
 [1 0]]
[[1 0]
 [0 1]
 [1 0]
 ...
 [0 1]
 [1 0]
 [0 1]]
(6398, 300) (6398, 2) (3554, 300) (3554, 2) (25872, 300) (25872, 2)


In [16]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py cora

Loaded Word Vectors!
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217

[[0 0 0 ... 0 0 1]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
[[1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
(1707, 300) (1707, 7) (812, 300) (812, 7) (3239, 300) (3239, 7)


In [17]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py pubmed

Loaded Word Vectors!
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217

[13802, 13803, 13804, 13805, 13806, 13807, 13808, 13809, 13810, 13811, 13812, 13813, 13814, 13815, 13816, 13817, 13818, 13819, 13820, 13821, 13822, 13823, 13824, 13825, 13826, 13827, 13828, 13829, 13830, 13831, 13832, 13833, 13834, 13835, 13836, 13837, 13838, 13839, 13840, 13841, 13842, 13843, 13844, 13845, 13846, 13847, 13848, 13849, 13850, 13851, 13852, 13853, 13854, 13855, 13856, 13857, 13858, 13859, 13860, 13861, 13862, 13863, 13864, 13865, 13866, 13867, 13868, 13869, 13870, 13871, 13872, 13873, 13874, 13875, 13876, 13877, 13878, 13879, 13880, 13881, 13882, 13883, 13884, 13885, 13886, 13887, 13888, 13889, 13890, 13891, 13892, 13893, 13894, 13895, 13896, 13897, 13898, 13899, 13900, 13901, 13902, 13903, 13904, 13905, 13906, 13907, 13908, 13909, 13910, 13911, 13912, 13913, 13914, 13915, 13916, 13917, 13918, 13919, 13920, 13921, 13922, 13923, 13924, 13925, 13926, 13927, 13928, 13929, 13930, 13931, 13932, 13933, 13934, 13935, 13936, 13937, 13938, 13939, 13940, 13941, 13942, 13943, 13944

[2399, 11014, 10670, 11768, 3013, 9063, 1143, 466, 1839, 13547, 5518, 3977, 2342, 7859, 646, 7303, 3289, 11058, 8567, 6190, 4948, 9552, 2836, 7227, 6398, 13573, 12399, 5827, 1272, 502, 13609, 2005, 509, 9261, 423, 9878, 4350, 9542, 13086, 148, 8192, 1309, 10860, 5624, 10035, 5347, 11534, 12010, 2827, 8205, 9089, 11652, 2164, 3601, 7004, 7457, 419, 6524, 4804, 7098, 1183, 10033, 11279, 3918, 6620, 3837, 5780, 11208, 8488, 4885, 12311, 619, 10507, 3836, 13517, 10830, 10940, 9380, 3061, 3029, 1630, 20, 2826, 10677, 7903, 325, 9151, 4803, 7868, 11496, 10569, 8680, 8734, 9099, 1853, 6731, 6468, 12763, 12210, 6673, 11678, 2196, 5222, 7545, 3965, 1421, 6986, 5960, 6252, 11148, 10172, 8767, 2751, 2773, 8217, 10682, 444, 1357, 8472, 8137, 10206, 1460, 9148, 11936, 2152, 2001, 10438, 5173, 2583, 7314, 2764, 235, 9608, 9315, 7534, 7473, 8245, 5047, 1916, 5527, 12686, 143, 2010, 7772, 3747, 7320, 13303, 12594, 2416, 11571, 3633, 10545, 7798, 10695, 10220, 6130, 9642, 3721, 1273, 3176, 725, 13341, 

[[0 0 1]
 [0 0 1]
 [0 0 1]
 ...
 [1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]
 ...
 [0 1 0]
 [1 0 0]
 [0 0 1]]
(12422, 300) (12422, 3) (5915, 300) (5915, 3) (14254, 300) (14254, 3)


In [18]:
!../gcn_text_categorization/venv/bin/python3 build_graph.py citeseer

Loaded Word Vectors!
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217

[2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 248

[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 ...
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]]
[[0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 ...
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]]
(2088, 300) (2088, 6) (993, 300) (993, 6) (5834, 300) (5834, 6)


In [19]:
!../gcn_text_categorization/venv/bin/python3 train.py 20ng

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0040 train_loss= 0.39791 train_acc= 0.93717 val_loss= 0.51687 val_acc= 0.89920 time= 34.92011
Epoch: 0041 train_loss= 0.37412 train_acc= 0.93982 val_loss= 0.50004 val_acc= 0.90009 time= 35.37020
Epoch: 0042 train_loss= 0.35325 train_acc= 0.94385 val_loss= 0.48467 val_acc= 0.90274 time= 35.82573
Epoch: 0043 train_loss= 0.33335 train_acc= 0.94601 val_loss= 0.47015 val_acc= 0.90097 time= 36.34828
Epoch: 0044 train_loss= 0.31727 train_acc= 0.94631 val_loss= 0.45673 val_acc= 0.90009 time= 36.01178
Epoch: 0045 train_loss= 0.30160 train_acc= 0.94758 val_loss= 0.44390 val_acc= 0.90186 time= 35.86705
Epoch: 0046 train_loss= 0.28586 train_acc= 0.95210 val_loss= 0.43230 val_acc= 0.90274 time= 35.88526
Epoch: 0047 train_loss= 0.27243 train_acc= 0.95357 val_loss= 0.42160 val_acc= 0.90451 time= 34.93063
Epoch: 0048 train_loss= 0.26001 train_acc= 0.95397 val_loss= 0.41246 val_acc= 0.90628 time= 34.69502
Epoch: 0049 train_loss= 0.24774 train_acc= 0.95573 val_loss= 0.40469 val_acc= 0.90716 time=

(0.8599923125488976, 0.857323065461647, 0.8578520561388283, None)
Micro average Test Precision, Recall and F1-Score...
(0.8625862984599044, 0.8625862984599044, 0.8625862984599044, None)
embeddings:
42757 11314 7532
[[-0.02499219  0.08530699  0.22901587 ...  0.23670483  0.10629643
  -0.05675769]
 [-0.06614803  0.2020054   0.06871926 ... -0.00112144 -0.00141145
   0.24603972]
 [-0.08580923  0.32211903 -0.03723945 ... -0.02275528  0.4352045
   0.00134831]
 ...
 [ 0.3549305   0.3320478   0.32095474 ... -0.08663112  0.31338367
   0.00941881]
 [ 0.12318446  0.18399532  0.10349795 ...  0.25170243  0.20808704
   0.13996033]
 [ 0.26681307 -0.01973211 -0.09330142 ... -0.1254698  -0.01597182
  -0.09072962]]


In [20]:
!../gcn_text_categorization/venv/bin/python3 train.py R8

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0041 train_loss= 0.24860 train_acc= 0.94247 val_loss= 0.30081 val_acc= 0.91059 time= 3.25130
Epoch: 0042 train_loss= 0.24166 train_acc= 0.95118 val_loss= 0.29140 val_acc= 0.91423 time= 3.28288
Epoch: 0043 train_loss= 0.22868 train_acc= 0.95239 val_loss= 0.28237 val_acc= 0.91423 time= 3.22938
Epoch: 0044 train_loss= 0.21924 train_acc= 0.95179 val_loss= 0.27358 val_acc= 0.91423 time= 3.25385
Epoch: 0045 train_loss= 0.20862 train_acc= 0.95462 val_loss= 0.26493 val_acc= 0.91423 time= 3.23230
Epoch: 0046 train_loss= 0.20072 train_acc= 0.95563 val_loss= 0.25650 val_acc= 0.91971 time= 3.31152
Epoch: 0047 train_loss= 0.18982 train_acc= 0.95969 val_loss= 0.24827 val_acc= 0.91971 time= 3.24307
Epoch: 0048 train_loss= 0.17603 train_acc= 0.96151 val_loss= 0.24043 val_acc= 0.91971 time= 3.26890
Epoch: 0049 train_loss= 0.16921 train_acc= 0.96212 val_loss= 0.23285 val_acc= 0.92336 time= 3.25032
Epoch: 0050 train_loss= 0.16242 train_acc= 0.96394 val_loss= 0.22575 val_acc= 0.92336 time= 3.20105


In [21]:
!../gcn_text_categorization/venv/bin/python3 train.py R52

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0041 train_loss= 0.89673 train_acc= 0.80625 val_loss= 0.91892 val_acc= 0.78407 time= 4.98140
Epoch: 0042 train_loss= 0.86986 train_acc= 0.81782 val_loss= 0.89559 val_acc= 0.79326 time= 5.01294
Epoch: 0043 train_loss= 0.84883 train_acc= 0.82479 val_loss= 0.87254 val_acc= 0.80398 time= 5.00401
Epoch: 0044 train_loss= 0.82743 train_acc= 0.82939 val_loss= 0.84966 val_acc= 0.81470 time= 5.00068
Epoch: 0045 train_loss= 0.80353 train_acc= 0.83432 val_loss= 0.82736 val_acc= 0.82083 time= 4.92956
Epoch: 0046 train_loss= 0.77948 train_acc= 0.83874 val_loss= 0.80584 val_acc= 0.82389 time= 5.00783
Epoch: 0047 train_loss= 0.76175 train_acc= 0.83857 val_loss= 0.78509 val_acc= 0.82848 time= 4.96979
Epoch: 0048 train_loss= 0.74252 train_acc= 0.84401 val_loss= 0.76540 val_acc= 0.83767 time= 4.94075
Epoch: 0049 train_loss= 0.71877 train_acc= 0.85065 val_loss= 0.74658 val_acc= 0.84073 time= 4.91789
Epoch: 0050 train_loss= 0.70083 train_acc= 0.85286 val_loss= 0.72875 val_acc= 0.84686 time= 5.00024


Epoch: 0123 train_loss= 0.09973 train_acc= 0.98060 val_loss= 0.25387 val_acc= 0.94334 time= 4.93991
Epoch: 0124 train_loss= 0.09478 train_acc= 0.98196 val_loss= 0.25239 val_acc= 0.94640 time= 5.01662
Epoch: 0125 train_loss= 0.09970 train_acc= 0.98247 val_loss= 0.25001 val_acc= 0.94487 time= 4.97501
Epoch: 0126 train_loss= 0.09290 train_acc= 0.98383 val_loss= 0.24710 val_acc= 0.93874 time= 4.95538
Epoch: 0127 train_loss= 0.09182 train_acc= 0.98196 val_loss= 0.24465 val_acc= 0.94027 time= 4.89359
Epoch: 0128 train_loss= 0.08720 train_acc= 0.98452 val_loss= 0.24169 val_acc= 0.94027 time= 4.98143
Epoch: 0129 train_loss= 0.09011 train_acc= 0.98145 val_loss= 0.23984 val_acc= 0.94487 time= 4.96793
Epoch: 0130 train_loss= 0.08598 train_acc= 0.98162 val_loss= 0.23961 val_acc= 0.94793 time= 4.95240
Epoch: 0131 train_loss= 0.08559 train_acc= 0.98486 val_loss= 0.23858 val_acc= 0.94793 time= 4.95208
Epoch: 0132 train_loss= 0.08345 train_acc= 0.98315 val_loss= 0.23876 val_acc= 0.94487 time= 4.93506


(0.9373052959501558, 0.9373052959501558, 0.9373052959501558, None)
embeddings:
8892 6532 2568
[[ 0.07366288  0.0573433   1.066707   ...  0.16071995  0.00444491
   0.01221579]
 [ 0.09823257  0.26147136  0.3431985  ...  0.2355781   0.08712645
   0.26273817]
 [ 0.39660087  0.14442872  0.14464179 ...  0.1732119   0.38193017
   0.13150835]
 ...
 [ 0.30608496  0.32896084 -0.01018698 ...  0.2838948   0.30245915
   0.3207655 ]
 [ 0.05939741  0.07992201  0.474935   ...  0.05394033  0.12218754
   0.06765496]
 [ 0.21085416 -0.05716043  0.8967128  ... -0.06262571  0.1066458
   0.03218646]]


In [22]:
!../gcn_text_categorization/venv/bin/python3 train.py ohsumed

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0041 train_loss= 1.21739 train_acc= 0.70913 val_loss= 1.49628 val_acc= 0.60000 time= 8.76159
Epoch: 0042 train_loss= 1.17182 train_acc= 0.71509 val_loss= 1.46817 val_acc= 0.60597 time= 9.00094
Epoch: 0043 train_loss= 1.12705 train_acc= 0.72601 val_loss= 1.44184 val_acc= 0.61791 time= 9.01627
Epoch: 0044 train_loss= 1.07580 train_acc= 0.74652 val_loss= 1.41809 val_acc= 0.62090 time= 8.85852
Epoch: 0045 train_loss= 1.03880 train_acc= 0.75248 val_loss= 1.39590 val_acc= 0.62388 time= 8.88248
Epoch: 0046 train_loss= 0.98834 train_acc= 0.76803 val_loss= 1.37541 val_acc= 0.62687 time= 9.01981
Epoch: 0047 train_loss= 0.94480 train_acc= 0.77730 val_loss= 1.35579 val_acc= 0.65075 time= 8.79000
Epoch: 0048 train_loss= 0.90978 train_acc= 0.78822 val_loss= 1.33676 val_acc= 0.65373 time= 9.12023
Epoch: 0049 train_loss= 0.86852 train_acc= 0.79583 val_loss= 1.31665 val_acc= 0.65075 time= 9.03020
Epoch: 0050 train_loss= 0.82653 train_acc= 0.80542 val_loss= 1.29901 val_acc= 0.64776 time= 9.15311


In [23]:
!../gcn_text_categorization/venv/bin/python3 train.py mr

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

In [24]:
!../gcn_text_categorization/venv/bin/python3 train.py cora

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0042 train_loss= 0.48227 train_acc= 0.85764 val_loss= 0.64246 val_acc= 0.80423 time= 0.41336
Epoch: 0043 train_loss= 0.46793 train_acc= 0.85764 val_loss= 0.63810 val_acc= 0.79894 time= 0.39367
Epoch: 0044 train_loss= 0.43793 train_acc= 0.86526 val_loss= 0.64070 val_acc= 0.78307 time= 0.39558
Epoch: 0045 train_loss= 0.43651 train_acc= 0.86409 val_loss= 0.63331 val_acc= 0.78836 time= 0.39513
Epoch: 0046 train_loss= 0.41552 train_acc= 0.87288 val_loss= 0.61895 val_acc= 0.80952 time= 0.40026
Epoch: 0047 train_loss= 0.39459 train_acc= 0.87932 val_loss= 0.61110 val_acc= 0.81481 time= 0.40176
Epoch: 0048 train_loss= 0.38610 train_acc= 0.88166 val_loss= 0.60715 val_acc= 0.80952 time= 0.38066
Epoch: 0049 train_loss= 0.37335 train_acc= 0.88518 val_loss= 0.60443 val_acc= 0.80952 time= 0.41217
Epoch: 0050 train_loss= 0.35844 train_acc= 0.89221 val_loss= 0.60775 val_acc= 0.80423 time= 0.39978
Epoch: 0051 train_loss= 0.34978 train_acc= 0.90158 val_loss= 0.61010 val_acc= 0.79894 time= 0.39273


In [25]:
!../gcn_text_categorization/venv/bin/python3 train.py pubmed

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0041 train_loss= 0.43376 train_acc= 0.82794 val_loss= 0.44126 val_acc= 0.81594 time= 1.70741
Epoch: 0042 train_loss= 0.42777 train_acc= 0.82931 val_loss= 0.43862 val_acc= 0.81522 time= 1.66540
Epoch: 0043 train_loss= 0.42736 train_acc= 0.82665 val_loss= 0.44076 val_acc= 0.82029 time= 1.68414
Epoch: 0044 train_loss= 0.42093 train_acc= 0.83132 val_loss= 0.44287 val_acc= 0.82102 time= 1.69708
Epoch: 0045 train_loss= 0.41686 train_acc= 0.83228 val_loss= 0.43165 val_acc= 0.81594 time= 1.69290
Epoch: 0046 train_loss= 0.40720 train_acc= 0.83736 val_loss= 0.43082 val_acc= 0.82029 time= 1.73460
Epoch: 0047 train_loss= 0.41312 train_acc= 0.83711 val_loss= 0.43103 val_acc= 0.82029 time= 1.72384
Epoch: 0048 train_loss= 0.42392 train_acc= 0.82456 val_loss= 0.43168 val_acc= 0.82609 time= 1.68667
Epoch: 0049 train_loss= 0.41315 train_acc= 0.83446 val_loss= 0.42852 val_acc= 0.82754 time= 1.67885
Epoch: 0050 train_loss= 0.40743 train_acc= 0.83816 val_loss= 0.42061 val_acc= 0.82536 time= 1.67674


In [26]:
!../gcn_text_categorization/venv/bin/python3 train.py citeseer

/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/4tb/nabarun/nlp/gcn_text_categorization/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/4tb/nabarun/

Epoch: 0042 train_loss= 0.46443 train_acc= 0.84675 val_loss= 0.73623 val_acc= 0.76623 time= 1.11173
Epoch: 0043 train_loss= 0.44825 train_acc= 0.85489 val_loss= 0.74341 val_acc= 0.74892 time= 1.06022
Early stopping...
Optimization Finished!
Test set results: cost= 0.84323 accuracy= 0.72205 time= 0.20332
6827
Test Precision, Recall and F1-Score...
              precision    recall  f1-score   support

           0     0.6864    0.7989    0.7384       189
           1     0.7746    0.7933    0.7838       208
           2     0.7603    0.7400    0.7500       150
           3     0.7225    0.7977    0.7582       173
           4     0.7095    0.6225    0.6632       204
           5     0.5682    0.3623    0.4425        69

    accuracy                         0.7221       993
   macro avg     0.7036    0.6858    0.6894       993
weighted avg     0.7189    0.7221    0.7171       993

Macro average Test Precision, Recall and F1-Score...
(0.7035796016968807, 0.6857944585283766, 0.689356550334